### ISSUE TITLE
wekan-0.11.0.tar.gz

### ISSUE THREAD

**Issue by anselal** [soohwa/sps#1]
Hi,

can you let me know where yo found the file `https://github.com/wefork/wekan/files/681473/wekan-0.11.0.tar.gz` ? This file did not exist in the project nor is part of of the release.

**Comment by soohwa** [comment]
Hi,

I know this issue may be old but that URL was provided by the temporary fork of wekan.

I just tested it and it worked :-) but if you prefer I just reupload the file into my repository. So i updated the wekan.md too.

https://github.com/soohwa/sps/commit/08ad7c31618b665fa5e44491a28d64153584777d
Thx
