### ISSUE TITLE
Can I move sps to Wekan organization?

### ISSUE THREAD

**Issue by xet7** [soohwa/sps#2]
Hi,
can I move sps to Wekan organization?
That way I could also make modifications under Wekan org.
I would also give you access at Wekan organization.

**Comment by soohwa** [comment]
Oh yes, no problem and thank you ! I'm very pleased ^^ :-)

**Comment by xet7** [comment]
@soohwa 

I moves sps to Wekan and invited you to Wekan team:
https://github.com/wekan/sps
